version: '3.8'

services: 
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes: 
      - .:/apps
    ports: 
      - "8000:8000"
    depends_on: 
      - pgdb
  pgdb:
      image: postgres
      container_name: pgdb
      volumes: 
        - postgres_data:/var/lib/postgresql/data/
      environment: 
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
volumes: 
  postgres_data:
